name: Build and publish package to npmjs everytime a new release is created

# The workflow below runs anytime the release event with type created occurs.
on:
  release:
    types: [created]

jobs:
  publish-npm:
    
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/main
      - run: npm run build
      
      - uses: papeloto/action-zip@v1
        with:
          files: dist
          dest: .zip
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.zip"

#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
