name: Build and publish package to npmjs everytime a new release is created

# The workflow below runs anytime the release event with type created occurs.
on:
  release:
    types: [ created ]

jobs:
  publish-npm:
    
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/main
      - run: npm run build

      - uses: papeloto/action-zip@v1
        with:
          files: dist
          dest: .zip

      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}.zip ./dist/@openglobus -x "*.map"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
